let products = [
  {
    id: 1,
    img: "img/feature-product/balo-nam-nu-phien-ban-han-quoc-phong-cach-hoang-da-Avril-96915.jpg",
    name: "Balo unisex hàn quốc nam nữ Avril 9691",
    desc: `Chất liệu bền bỉ với lớp vải polyester có khả năng kháng nước tốt. Thể tích lên đến 16 lít, giúp người dùng chứa đồ dùng thoải mái. Thiết kế đa ngăn, sức chứa rộng rãi, có thể để vừa laptop 15.6 inch. Kích thước 30.5x11x42.5 cm.<br> 
            <span style="color: rgb(255, 0, 0)">Bảo hành chính hãng 24 tháng.</span>`,
    firstPrice: "400.000",
    Price: "340.000",
  },
  {
    id: 2,
    img: "img/feature-product/balo-nam-nu-phien-ban-han-quoc-phong-cach-hoang-da-Avril-976320.jpg",
    name: "Balo unisex thời trang Hàn Quốc AWR9763",
    desc: `Chất liệu bền bỉ với lớp vải polyester có khả năng kháng nước tốt. Thể tích lên đến 16 lít, giúp người dùng chứa đồ dùng thoải mái. Thiết kế đa ngăn, sức chứa rộng rãi, có thể để vừa laptop 15.6 inch. Kích thước 30.5x11x42.5 cm.<br> <span style="color: rgb(255, 0, 0)">Bảo hành chính hãng 24 tháng.</span>`,
    firstPrice: "400.000",
    Price: "360.000",
  },
  {
    id: 3,
    img: "img/feature-product/balo-nam-nu-phien-ban-han-quoc-phong-cach-hoang-da-Avril-976322.jpg",
    name: "Balo unisex thời trang Hàn Quốc AWR9763",
    desc: `Chất liệu bền bỉ với lớp vải polyester có khả năng kháng nước tốt. Thể tích lên đến 16 lít, giúp người dùng chứa đồ dùng thoải mái. Thiết kế đa ngăn, sức chứa rộng rãi, có thể để vừa laptop 15.6 inch. Kích thước 30.5x11x42.5 cm.<br> <span style="color: rgb(255, 0, 0)">Bảo hành chính hãng 24 tháng.</span>`,
    firstPrice: "400.000",
    Price: "340.000",
  },
  {
    id: 4,
    img: "img/feature-product/balo-nam-nu-phien-ban-han-quoc-phong-cach-hoang-da-Avril-97634.jpg",
    name: "Balo unisex thời trang Hàn Quốc AWR9763",
    desc: `Chất liệu bền bỉ với lớp vải polyester có khả năng kháng nước tốt. Thể tích lên đến 16 lít, giúp người dùng chứa đồ dùng thoải mái. Thiết kế đa ngăn, sức chứa rộng rãi, có thể để vừa laptop 15.6 inch. Kích thước 30.5x11x42.5 cm.<br> <span style="color: rgb(255, 0, 0)">Bảo hành chính hãng 24 tháng.</span>`,
    firstPrice: "400.000",
    Price: "340.000",
  },
  {
    id: 5,
    img: "img/feature-product/balo-thoi-trang-han-quoc-balo-laptop-Q2103.jpg",
    name: "Balo unisex thời trang hàn quốc nam nữ Q210",
    desc: `Chất liệu bền bỉ với lớp vải polyester có khả năng kháng nước tốt. Thể tích lên đến 16 lít, giúp người dùng chứa đồ dùng thoải mái. Thiết kế đa ngăn, sức chứa rộng rãi, có thể để vừa laptop 15.6 inch. Kích thước 30.5x11x42.5 cm.<br> <span style="color: rgb(255, 0, 0)">Bảo hành chính hãng 24 tháng.</span>`,
    firstPrice: "380.000",
    Price: "290.000",
  },
  {
    id: 6,
    img: "img/feature-product/balo-thoi-trang-unisex-han-quoc-c35810.jpg",
    name: "Balo unisex thời trang hàn quốc nam nữ C358",
    desc: `Chất liệu bền bỉ với lớp vải polyester có khả năng kháng nước tốt. Thể tích lên đến 16 lít, giúp người dùng chứa đồ dùng thoải mái. Thiết kế đa ngăn, sức chứa rộng rãi, có thể để vừa laptop 15.6 inch. Kích thước 30.5x11x42.5 cm.<br> <span style="color: rgb(255, 0, 0)">Bảo hành chính hãng 24 tháng.</span>`,
    firstPrice: "",
    Price: "340.000",
  },
  {
    id: 7,
    img: "img/feature-product/balo-thoi-trang-unisex-han-quoc-nam-nu-Avril-971610.jpg",
    name: "Balo unisex thời trang Hàn Quốc Avril 9716",
    desc: `Chất liệu bền bỉ với lớp vải polyester có khả năng kháng nước tốt. Thể tích lên đến 16 lít, giúp người dùng chứa đồ dùng thoải mái. Thiết kế đa ngăn, sức chứa rộng rãi, có thể để vừa laptop 15.6 inch. Kích thước 30.5x11x42.5 cm.<br> <span style="color: rgb(255, 0, 0)">Bảo hành chính hãng 24 tháng.</span>`,
    firstPrice: "400.000",
    Price: "340.000",
  },
  {
    id: 8,
    img: "img/feature-product/balo-thoi-trang-unisex-han-quoc-nam-nu-Avril-97168.jpg",
    name: "Balo unisex thời trang Hàn Quốc Avril 9716",
    desc: `Chất liệu bền bỉ với lớp vải polyester có khả năng kháng nước tốt. Thể tích lên đến 16 lít, giúp người dùng chứa đồ dùng thoải mái. Thiết kế đa ngăn, sức chứa rộng rãi, có thể để vừa laptop 15.6 inch. Kích thước 30.5x11x42.5 cm.<br> <span style="color: rgb(255, 0, 0)">Bảo hành chính hãng 24 tháng.</span>`,
    firstPrice: "400.000",
    Price: "340.000",
  },
  {
    id: 9,
    img: "img/new-arrival-product/1.jpg",
    name: "Balo laptop nam thời trang Ozuko",
    desc: `Chất liệu bền bỉ với lớp vải polyester có khả năng kháng nước tốt. Thể tích lên đến 16 lít, giúp người dùng chứa đồ dùng thoải mái. Thiết kế đa ngăn, sức chứa rộng rãi, có thể để vừa laptop 15.6 inch. Kích thước 30.5x11x42.5 cm.<br> <span style="color: rgb(255, 0, 0)">Bảo hành chính hãng 24 tháng.</span>`,
    firstPrice: "1.200.000",
    Price: "1.080.000",
  },
  {
    id: 10,
    img: "img/new-arrival-product/2.jpg",
    name: "Balo đa năng công suất lớn MOYYI 854",
    desc: `Chất liệu bền bỉ với lớp vải polyester có khả năng kháng nước tốt. Thể tích lên đến 16 lít, giúp người dùng chứa đồ dùng thoải mái. Thiết kế đa ngăn, sức chứa rộng rãi, có thể để vừa laptop 15.6 inch. Kích thước 30.5x11x42.5 cm.<br> <span style="color: rgb(255, 0, 0)">Bảo hành chính hãng 24 tháng.</span>`,
    firstPrice: "999.000",
    Price: "850.000",
  },
  {
    id: 11,
    img: "img/new-arrival-product/3.jpg",
    name: "Balo đa năng công suất lớn MOYYI 853",
    desc: `Chất liệu bền bỉ với lớp vải polyester có khả năng kháng nước tốt. Thể tích lên đến 16 lít, giúp người dùng chứa đồ dùng thoải mái. Thiết kế đa ngăn, sức chứa rộng rãi, có thể để vừa laptop 15.6 inch. Kích thước 30.5x11x42.5 cm.<br> <span style="color: rgb(255, 0, 0)">Bảo hành chính hãng 24 tháng.</span>`,
    firstPrice: "1.190.000",
    Price: "900.000",
  },
  {
    id: 12,
    img: "img/new-arrival-product/4.jpg",
    name: "Balo laptop Ozuko 868",
    desc: `Chất liệu bền bỉ với lớp vải polyester có khả năng kháng nước tốt. Thể tích lên đến 16 lít, giúp người dùng chứa đồ dùng thoải mái. Thiết kế đa ngăn, sức chứa rộng rãi, có thể để vừa laptop 15.6 inch. Kích thước 30.5x11x42.5 cm.<br> <span style="color: rgb(255, 0, 0)">Bảo hành chính hãng 24 tháng.</span>`,
    firstPrice: "1.190.000",
    Price: "900.000",
  },
  {
    id: 13,
    img: "img/new-arrival-product/5.jpg",
    name: "Balo laptop thời trang Arctic Hunter 858",
    desc: `Chất liệu bền bỉ với lớp vải polyester có khả năng kháng nước tốt. Thể tích lên đến 16 lít, giúp người dùng chứa đồ dùng thoải mái. Thiết kế đa ngăn, sức chứa rộng rãi, có thể để vừa laptop 15.6 inch. Kích thước 30.5x11x42.5 cm.<br> <span style="color: rgb(255, 0, 0)">Bảo hành chính hãng 24 tháng.</span>`,
    firstPrice: "900.000",
    Price: "750.000",
  },
  {
    id: 14,
    img: "img/new-arrival-product/6.jpg",
    name: "BALO DA C376",
    desc: `Chất liệu bền bỉ với lớp vải polyester có khả năng kháng nước tốt. Thể tích lên đến 16 lít, giúp người dùng chứa đồ dùng thoải mái. Thiết kế đa ngăn, sức chứa rộng rãi, có thể để vừa laptop 15.6 inch. Kích thước 30.5x11x42.5 cm.<br> <span style="color: rgb(255, 0, 0)">Bảo hành chính hãng 24 tháng.</span>`,
    firstPrice: "550.000",
    Price: "400.000",
  },
  {
    id: 15,
    img: "img/new-arrival-product/7.jpg",
    name: "Balo Unisex thời trang nam nữ 681 – Đen",
    desc: `Chất liệu bền bỉ với lớp vải polyester có khả năng kháng nước tốt. Thể tích lên đến 16 lít, giúp người dùng chứa đồ dùng thoải mái. Thiết kế đa ngăn, sức chứa rộng rãi, có thể để vừa laptop 15.6 inch. Kích thước 30.5x11x42.5 cm.<br> <span style="color: rgb(255, 0, 0)">Bảo hành chính hãng 24 tháng.</span>`,
    firstPrice: "500.000",
    Price: "430.000",
  },
  {
    id: 16,
    img: "img/new-arrival-product/8.jpg",
    name: "Balo hàn quốc canvas",
    desc: `Chất liệu bền bỉ với lớp vải polyester có khả năng kháng nước tốt. Thể tích lên đến 16 lít, giúp người dùng chứa đồ dùng thoải mái. Thiết kế đa ngăn, sức chứa rộng rãi, có thể để vừa laptop 15.6 inch. Kích thước 30.5x11x42.5 cm.<br> <span style="color: rgb(255, 0, 0)">Bảo hành chính hãng 24 tháng.</span>`,
    firstPrice: "700.000",
    Price: "570.000",
  },
  {
    id: 17,
    img: "img/new-arrival-product/9.jpg",
    name: "Balo Unisex thời trang nam nữ 618",
    desc: `Chất liệu bền bỉ với lớp vải polyester có khả năng kháng nước tốt. Thể tích lên đến 16 lít, giúp người dùng chứa đồ dùng thoải mái. Thiết kế đa ngăn, sức chứa rộng rãi, có thể để vừa laptop 15.6 inch. Kích thước 30.5x11x42.5 cm.<br> <span style="color: rgb(255, 0, 0)">Bảo hành chính hãng 24 tháng.</span>`,
    firstPrice: "400.000",
    Price: "350.000",
  },
  {
    id: 18,
    img: "img/new-arrival-product/10.jpg",
    name: "Balo nam nữ Unisex thời trang Hàn Quốc Ulzzang",
    desc: `Chất liệu bền bỉ với lớp vải polyester có khả năng kháng nước tốt. Thể tích lên đến 16 lít, giúp người dùng chứa đồ dùng thoải mái. Thiết kế đa ngăn, sức chứa rộng rãi, có thể để vừa laptop 15.6 inch. Kích thước 30.5x11x42.5 cm.<br> <span style="color: rgb(255, 0, 0)">Bảo hành chính hãng 24 tháng.</span>`,
    firstPrice: "400.000",
    Price: "360.000",
  },
  {
    id: 19,
    img: "img/new-arrival-product/11.jpg",
    name: "Balo DA Q251",
    desc: `Chất liệu bền bỉ với lớp vải polyester có khả năng kháng nước tốt. Thể tích lên đến 16 lít, giúp người dùng chứa đồ dùng thoải mái. Thiết kế đa ngăn, sức chứa rộng rãi, có thể để vừa laptop 15.6 inch. Kích thước 30.5x11x42.5 cm.<br> <span style="color: rgb(255, 0, 0)">Bảo hành chính hãng 24 tháng.</span>`,
    firstPrice: "400.000",
    Price: "340.000",
  },
  {
    id: 20,
    img: "img/new-arrival-product/12.jpg",
    name: "Balo unisex hàn quốc nam nữ Supreme 8608",
    desc: `Chất liệu bền bỉ với lớp vải polyester có khả năng kháng nước tốt. Thể tích lên đến 16 lít, giúp người dùng chứa đồ dùng thoải mái. Thiết kế đa ngăn, sức chứa rộng rãi, có thể để vừa laptop 15.6 inch. Kích thước 30.5x11x42.5 cm.<br> <span style="color: rgb(255, 0, 0)">Bảo hành chính hãng 24 tháng.</span>`,
    firstPrice: "1.200.000",
    Price: "990.000",
  },
];
export default products